idf_component_register(
    SRCS
        "app_main.c"
        "esp_openclaw_node_box_cmd.c"
        "esp_openclaw_node_box_display.c"
        "esp_openclaw_node_box_display_node_cmd.c"
    INCLUDE_DIRS
        "."
    REQUIRES
        esp-openclaw-node
        esp-openclaw-node-provisioning
        esp-box-3
        esp_app_format
        console
        esp_event
        esp_netif
        esp_timer
        esp_wifi
        espressif__cjson
        mbedtls
        nvs_flash
)
