idf_component_register(
    SRCS
        "app_main.c"
        "esp_openclaw_node_example_adc_node_cmd.c"
        "esp_openclaw_node_example_cmd.c"
        "esp_openclaw_node_example_gpio_node_cmd.c"
    INCLUDE_DIRS
        "."
    REQUIRES
        esp-openclaw-node
        esp-openclaw-node-provisioning
        esp_adc
        esp_app_format
        console
        esp_driver_gpio
        esp_event
        esp_netif
        esp_wifi
        espressif__cjson
        mbedtls
        nvs_flash
)
