#pragma once
/* Synthetic compile-time inputs. Never include a board's saved configuration. */
#define CONFIG_OPENCLAW_ROOM_WIFI_SSID ""
#define CONFIG_OPENCLAW_ROOM_WIFI_PASSWORD ""
#define CONFIG_OPENCLAW_ROOM_SETUP_CODE ""
#define CONFIG_OPENCLAW_ROOM_GATEWAY_HTTP_BASE_URL ""
#define CONFIG_OPENCLAW_ROOM_TALK_PROVIDER ""
#define CONFIG_OPENCLAW_ROOM_TALK_MODEL ""
#define CONFIG_OPENCLAW_ROOM_TALK_VOICE ""
#define CONFIG_OPENCLAW_ROOM_CALL_IDLE_SECONDS 60
#ifndef CONFIG_LOG_DYNAMIC_LEVEL_CONTROL
#define CONFIG_LOG_DYNAMIC_LEVEL_CONTROL 1
#endif
#ifndef CONFIG_LOG_TAG_LEVEL_IMPL_NONE
#define CONFIG_LOG_TAG_LEVEL_IMPL_NONE 0
#endif
#ifndef CONFIG_LOG_DEFAULT_LEVEL
#define CONFIG_LOG_DEFAULT_LEVEL 3
#endif
#ifndef CONFIG_LOG_MAXIMUM_LEVEL
#define CONFIG_LOG_MAXIMUM_LEVEL 3
#endif
#define CONFIG_LOG_MASTER_LEVEL 0
