#pragma once
/* Synthetic compile-time inputs. Never include a board's saved configuration. */
#define CONFIG_OPENCLAW_ROOM_WIFI_SSID ""
#define CONFIG_OPENCLAW_ROOM_WIFI_PASSWORD ""
#define CONFIG_OPENCLAW_ROOM_SETUP_CODE ""
#define CONFIG_OPENCLAW_ROOM_GATEWAY_HTTP_BASE_URL ""
#define CONFIG_OPENCLAW_ROOM_TALK_PROVIDER ""
#define CONFIG_OPENCLAW_ROOM_TALK_MODEL ""
#define CONFIG_OPENCLAW_ROOM_TALK_VOICE ""
#define CONFIG_OPENCLAW_ROOM_CALL_IDLE_SECONDS 60
