#pragma once

enum {
    ROOM_TALK_VAD_SILENCE_MS = 400,
    ROOM_PLAYER_RAW_FIFO_BYTES = 4 * 1024,
    ROOM_PLAYER_RENDER_FIFO_BYTES = 6 * 1024,
    ROOM_PLAYER_RAW_FIFO_KIB = ROOM_PLAYER_RAW_FIFO_BYTES / 1024,
    ROOM_PLAYER_RENDER_FIFO_KIB = ROOM_PLAYER_RENDER_FIFO_BYTES / 1024,
};
