name: Push esp-openclaw-node to IDF Component Registry

on:
  push:
    branches:
      - main

jobs:
  upload_components:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: "recursive"

      - name: Upload esp-openclaw-node to IDF Component Registry
        uses: espressif/upload-components-ci-action@v2
        with:
          components: "esp-openclaw-node:components/esp-openclaw-node"
          namespace: "espressif"
